export interface Config {
  eula?: boolean;
  memory?: Record<string, string>;
  runningDirectory?: string;
  serverJarUri?: string;
  serverProperties?: Record<string, string>;
}

export const defaults: Config = {
  eula: false,
  runningDirectory: '/data',
  serverJarUri: 'https://papermc.io/api/v1/paper/1.16.2/latest/download',
  memory: {
    min: '1G',
    max: '1G',
  },
  serverProperties: {
    'enable-jmx-monitoring': 'false',
    'rcon.port': '25575',
    'level-seed': '',
    gamemode: 'survival',
    'enable-command-block': 'false',
    'enable-query': 'false',
    'generator-settings': '',
    'level-name': 'world',
    motd: 'A Node-Generated Minecraft Server',
    'query.port': '25565',
    pvp: 'true',
    'generate-structures': 'true',
    difficulty: 'easy',
    'network-compression-threshold': '256',
    'max-tick-time': '60000',
    'use-native-transport': 'true',
    'max-players': '20',
    'online-mode': 'true',
    'enabled-status': 'true',
    'allow-flight': 'false',
    'broadcast-rcon-to-ops': 'true',
    'view-distance': '10',
    'max-build-height': '256',
    'server-ip': '',
    'allow-nether': 'true',
    'server-port': '25565',
    'enable-rcon': 'false',
    'sync-chunk-writes': 'true',
    'op-permission-level': '4',
    'prevent-proxy-connections': 'false',
    'resource-pack': '',
    'entity-broadcast-range-percentage': '100',
    'rcon.password': '',
    'player-idle-timeout': '0',
    debug: 'false',
    'force-gamemode': 'false',
    'rate-limite': '0',
    hardcore: 'false',
    'white-list': 'false',
    'broadcast-console-to-ops': 'true',
    'spawn-npcs': 'true',
    'snooper-enabled': 'true',
    'function-permissions-level': '2',
    'level-type': 'default',
    'spawn-monsters': 'true',
    'enforce-whitelist': 'false',
    'resource-pack-sha1': '',
    'spawn-protection': '16',
    'max-world-size': '29999984',
  },
};
